<article>
<b>GV 2008 der Trachtengruppe Merenschwand</b>
<br>
<h1>Auch die Trachten sind jetzt im Web</h1>
<br>Zur diesj&auml;hrigen Generalversammlung konnte die Pr&auml;sidentin Margrit Heim-Fischer 40 Aktiv- und Ehrenmitglieder der Trachtengruppe in der Rest. Sonne, Benzenschwil, begr&uuml;ssen. Nach dem feinen Nachtessen blickten wir auf ein reichbefrachtetes 2007 zur&uuml;ck: Im Fr&uuml;hling fand ein aussergew&ouml;hnliches Festkonzert in unserer Kirche statt, zusammen mit f&uuml;nf Solisten und den M&auml;nnerch&ouml;ren Bergdietikon, Spreitenbach und Merenschwand. Beliebte Melodien aus Oper, Operette und Liedgesang unter der Chorleitung von Erika Riedo zog viel Volk aus nah und fern an. Im Weiteren wurde der Turnverein vom Eidgen&ouml;ssischen abgeholt, Mithilfe beim 20-Jahr-Jubil&auml;um des Ortsmuseums Postlonzihaus, Tanzen am Heimatabend in Rotkreuz und der H&ouml;hepunkt wie alle zwei Jahre unser unvergesslicher Heimatabend mit Theaterauff&uuml;hrung. Unser langj&auml;hriges Konzept, bei welchem wir das Singen und Tanzen im Vierakter „Uf de Sunnr&uuml;ti“ integrierten, gab uns mit der sehr guten Besucherzahl einmal mehr recht. Die weiteren Jahresberichte von der Singleiterin Erika Riedo, der Tanzleiterin Erica Fischer und der Kindertanzleiterin Karin Vogel rundeten den R&uuml;ckblick ab.
<br><br><i><b>Tausend Franken f&uuml;r Entlastungsdienst</b></i><br><br>
Der hohe Reinerl&ouml;s aus dem Adventswarenverkauf betrug tausend Franken und konnte dem Entlastungsdienst Aargau f&uuml;r Angeh&ouml;rige behinderter und chronisch kranker Menschen einbezahlt werden. Allen, die zu diesem erfreulichen Betrag beigetragen haben und auch der wohlwollenden K&auml;uferschaft vielen herzlichen Dank.
<br><br>
<i><b>Ehrungen</b></i><br>
Bei den Mutationen war erfreulicherweise ein Neueintritt mit Susanne Ritz zu verzeichnen, die wir im Chor willkommen heissen. Die Ehrenmitgliedschaft f&uuml;r 25 Jahre bekam Erica Fischer, verbunden mit einem grossen Merci, da sie doch seit mehr als 20 Jahre das Tanzen leitet. Einen Spezialapplaus gab es f&uuml;r 20 aktive Merenschwander Trachtenjahre; n&auml;mlich f&uuml;r Jakob Wiederkehr und f&uuml;r 30 Jahre Margrit und B&auml;rti Heim-Fischer. Der Probenplan im 07 mit je 35 Sing- und Tanzproben erforderte viel Pr&auml;senz, darum konnten nur wenig Kaffeel&ouml;ffeli und Blumen f&uuml;r sehr guten Probenbesuch an die Mitglieder verteilt werden. 
<br><br><br>
<i><b>www.trachtengruppe-merenschwand.ch</b></i><br><br>
Neu hat auch die Trachtengruppe eine eigene Homepage, die von dem Jungt&auml;nzer Adriano H&auml;nggli bewirtschaftet wird. Auf verschiedenen Seiten bekommen Sie einen Einblick von unseren letzten Vereinsjahren und auch „Aktuelles“. Sind Sie interessiert an unserem vielseitigen Jahresprogramm 2008, an einem Probenbesuch oder m&ouml;chten Sie Fotos von unseren letzten Theaterabend „Uf de Sunnr&uuml;ti“ anschauen, dann gehen Sie doch auf unsere Trachten-Homepage.
M&ouml;chten Sie gerne bei uns mitmachen, ob Erwachsen oder noch Kind? Dann gibt Ihnen gerne die Pr&auml;sidentin Margrit Heim Auskunft: Telefon 056 668 12 76 oder die weiteren Vorstandsmitglieder Erica Fischer, Monika Br&uuml;gger, Regula Schuler und Astrid Wiederkehr.
<br><br>
<div class="right">hsch</div>
</article>