<article>   <h1>Unvergessliche Apfelbl&uuml;tenpracht im Vinschgau (S&uuml;dtirol)</h1>
 

<h2>13.-15. April 2012</h2>
<br>
Im Herbst 2008 haben sich Christine und Peter Schmid ihren Traum erf&uuml;llt und sind ins S&uuml;dtirol ausgewandert. In Kastelbell im Vinschgau haben sie ihren Alterssitz gefunden. Trotz gr&ouml;sserer Distanz blieben sie weiterhin mit der Trachtenruppe Merenschwand verbunden. Es lag also auf der Hand, dass eine gr&ouml;ssere Gruppe unsere &quot;S&uuml;dtiroler&quot; einmal besuchen w&uuml;rden.<br>


<h2>1.Tag:</h2>
Am Freitagmorgen, 13. April 2012, stieg eine erwartungsvolle 15-k&ouml;pfige Schar in einen Kleinbus und liess sich von Heinz Seiler in sicherer Fahrt ins S&uuml;dtirol chauffieren. Die Fahrt f&uuml;hrte durchs Pr&auml;ttigau nach Klosters zum Bahnverlad Vereina und weiter nach Zernez, wo wir einen Mittagshalt einlegten. Die Hinreise f&uuml;hrte &uuml;ber den Ofenpass und durchs M&uuml;nstertal, wo wir bei Taufers die Landesgrenze passierten. Die kleinste Stadt Italiens namens Glurns mit den gut erhaltenen Stadtmauern und Toren, war schnell durchquert. Noch eine halbe Stunde Autofahrt durch die ersten bl&uuml;henden Apfelplantagen und wir kamen schon in Kastelbell an. Einzelne Mitreisende waren schon bei Christine und Peter zu Gast und so war es ein Leichtes, ihr Heim den &quot;Kuppelrainerhof&quot; zu finden. Wir wurden in ihrer grossen Wohnung mit Kaffee und Kuchen und einem echten Vinschger-Apfel herzlich begr&uuml;sst. Das grosse Bauernhaus steht mitten in den Apfelplantagen, von denen es im Vinschgau bis zum Kalternsee unz&auml;hlige gibt. Ihr Haus, wo Christine und Peter eingemietet sind, liegt am Dorfrand von Kastelbell. Daneben fliesst die Etsch und die Vinschgerbahn mit Bahnhof befindet sich ebenfalls in unmittelbarer N&auml;he. <br>
<br>
Nach der Kuchen-St&auml;rkung hiess es Abmarsch zum nahen Schloss Kastelbell, das nicht zu &uuml;bersehen ist auf einer Anh&ouml;he &uuml;ber dem Dorf. Auf interessante Art f&uuml;hrte uns ein junger Kunsthistoriker durch die R&auml;umlichkeiten und wusste vieles aus der Vergangenheit zu berichten. Die einmalige Lage des Schlosses beeindruckte mit einer sch&ouml;nen Aussicht auf die verschneiten Berge und &uuml;bers Tal Richtung Meran und talaufw&auml;rts Richtung Reschenpass.<br>
 <br>
S&uuml;dtirol ohne Weindegustation, das ist unvorstellbar. So war unser n&auml;chstes Ziel ein Weinkeller, der sich etwas oberhalb des Schlosses befand, das &quot;K&ouml;felgut&quot;. Martin Pohl empfing uns auf seinem Weingut zur einer &quot;Weinkost&quot;. Doch vor dem &quot;Zuprosten&quot; spazierten wir zum steilen Weinberg, wo er uns Wissenswertes &uuml;ber den Weinbau im Vinschgau erz&auml;hlte. (So gilt Martin Pohl sen. als Pionier f&uuml;r den Weinanbau im Vinschgau. Er begann 1970 Blauburgunder anzubauen.) Nachdem in der Nacht auf Ostermontag Frost herrschte (also 4 Tage vorher), erfuhren wir auch wie die Ostbauern mit einer &quot;Frostberegnung&quot; die Apfelbl&uuml;ten sch&uuml;tzen. - Bei der Weindegustation meinte Martin Pohl schmunzelnd: "Nur mit Wassertrinken sei die Stimmung wohl eher griesgr&auml;mig, aber mit Wein helle doch die Stimmung schnell auf und es werde gelacht!" - Abgerundet wurde die Degustation mit einem &quot;Marillenschnaps&quot; mit Marillen (Aprikosen) aus eigenem Anbau. Nat&uuml;rlich kauften wir noch einige Flaschen roten oder weissen Wein. Z&uuml;gigen Schrittes liefen wir nun zum &quot;Gstirnerhof&quot;, wo wir unsere netten Zimmer mit Fr&uuml;hst&uuml;ck bezogen. Ein gem&uuml;tliches Gasthaus, das man sich auch f&uuml;r Ferien, mit oder ohne Velo, vorstellen kann. Bei Christel f&uuml;hlten wir uns sofort gut aufgehoben.<br> 
<br>
Langsam knurrte der Magen und wir wurden im nahen &quot;Angergurterkeller&quot; zum Nachtessen erwartet. Ein sogenannter &quot;Hofschank&quot; mitten in Marein. (Marein ist eine der f&uuml;nf Fraktionen, die zusammen die Gemeinde Kastelbell-Tschars bilden.)
Uns wurde eine typische Kastelbeller Fr&uuml;hlings-Spezialit&auml;t serviert: Fl&auml;dlisuppe, weisse, einheimische Spargeln mit Bozner Sauce, Schinken und Salzkartoffeln. In Kastelbell finden allj&auml;hrlich die sogenannten &quot;Spargelwochen&quot; statt und wir durften den Start machen. Nach dem Gaumenschmaus brachte der Kellner zum Kaffee noch Marillen- und Mohnkrapfen. Ebenfalls eine feine Vinschgauer Spezialit&auml;t. Vor dem Abschied kam die Frage: &quot;Wer mag ein Schn&auml;psle?&quot; Man stellte uns wie selbstverst&auml;ndlich drei Flaschen verschiedene Schn&auml;pse und Gl&auml;ser auf den Tisch. Wir sollten uns nach belieben bedienen, es gehe auf Kosten des Hauses! Wir hatten die Wahl zwischen &quot;Schlehdorn&quot;, &quot;N&uuml;sseler&quot; oder &quot;Williams&quot;, oder versuchten gar alle drei. Bei ausgelassener Stimmung liefen wir zur&uuml;ck zum Nachtlager.<br>


<h2>2. Tag:</h2>
Der Samstag begannen wir mit einem reichhaltigen Fr&uuml;hst&uuml;ck mit S&uuml;dtiroler-Speck. Obwohl der Himmel wolkenverhangen war, schn&uuml;rten wir die Wanderschuhe, wie geplant. Wir marschierten auf dem Rad- und Wanderweg der Etsch entlang zum Nachbardorf Latsch zur Seilbahnstation. Die steile Seilbahn f&uuml;hrte uns hinauf nach St. Martin im Kofel. (Der Name r&uuml;hrt von einer alten Wallfahrtskapelle her, die 1510 erstmals erw&auml;hnt wurde und Martin von Tours, dem Patron der Herden geweiht ist.) Die kleine Kirche ist &uuml;ber eine Felsgrotte errichtet worden und von weit her im Tal unten sichtbar. Begleitet wurden wir von Franz Ratschiller, der auf St. Martin geboren und aufgewachsen ist. Er wusste manche Geschichte um das Kirchlein und der Pfarrherren zu berichten. Auf der H&ouml;henwanderung, die Richtung &quot;Eggh&ouml;fen&quot; f&uuml;hrte, erz&auml;hlte Herr Ratschiller im Vinschger Dialekt vom fr&uuml;heren, harten Leben dort oben. Wir sahen eine kleine H&uuml;tte aus Holz mit Schindeldach, in der fr&uuml;her bis zu 16 Personen lebten. Bei der Jausestation Egg gingen wir gerne in die warme Stube.<br>
<br>
Mit ortstypischen Spezialit&auml;ten liessen wir es uns einmal mehr gut gehen: Kn&ouml;del und Kaiserschmarren waren unsere Menue-Spitzenreiter. Vor dem Aufbruch hiess es wieder: &quot;Wollt ihr es Schn&auml;psle?&quot;. Wieder genehmigten die Meisten von uns einen selbstgemachten Lik&ouml;r aus der &quot;Zirbelkiefer&quot;. In bester Laune liessen wir uns draussen auf der grossen Terrasse noch fotografieren und machten uns auf den R&uuml;ckmarsch zur Seilbahnstation St. Martin. <br>
<br>
Endlich kam der langersehnte und versprochene S&uuml;dtiroler Sonnenschein, der 300 Tage im Jahr im S&uuml;dtirol anzutreffen sei. So spazierten wir zur&uuml;ck nach Kastelbell auf der alten Landstrasse durch die nicht enden wollenden Apfelplantagen, die in voller Bl&uuml;tenpracht standen. Ein wahres Fr&uuml;hlingserlebnis, das man nicht so schnell vergisst! Den Abend verbrachten wir im rustikalen und geschichtstr&auml;chtigen &quot;Gstirnerkeller&quot; und liessen den Tag mit dem Nachtessen ausklingen. Zur &Uuml;berraschung aller spielten noch einheimische Musikanten auf.<br>


<h2>3. Tag:</h2>
Nach dem Sonntags-Fr&uuml;hst&uuml;ck hiess es f&uuml;r die Meisten bereits wieder von Kastelbell  Abschied nehmen. Der musikalische Abschied machte der Musikverein von Kastelbell, der in seiner Vinschger Tracht kurz zu sehen und zu h&ouml;ren war, denn es war Kircheinzug zum Weissen Sonntag. <br>
<br>
Auf dem Heimweg machte Heinz aber im Vinschgau noch mal kurz Halt, damit wir den Daheimgebliebenen einen echten &quot;S&uuml;dtiroler-Speck&quot; kaufen konnten.<br>
Die R&uuml;ckreise f&uuml;hrte &uuml;ber den Reschenpass, dem Reschensee vorbei, &uuml;ber die Norberth&ouml;he nach Martina ins Unterengadin. Weiter ging die Fahrt dem Inn entlang nach Lavin und via Vereinatunnel durchs Pr&auml;ttigau zur&uuml;ck nach Merenschwand. <br>
<br>
Wenn Christine und Peter die Absicht hatten, uns das S&uuml;dtirol und insbesondere den Vinschgau &quot;gluschtig&quot; zu machen, dann ist ihnen dies vollauf gelungen. Vieles haben wir erlebt und vieles gesehen, die drei Tage bleiben unvergesslich und machen Lust auf mehr!
<br>

<div class="right">Peter Schmid und Hanni Schriber-Neiger </div>
</article>