<h2>Proben 2015</h2><b>Die Tanzproben beginnen um 20.00 Uhr und finden im UG der Mehrzweckhalle statt.</b> 
<br>
<br><br>
<center><img src="./images/galerie/2014/01/bilder/0002.jpg"></center><br>

<table border="0" align="center" cellpadding="0" cellspacing="0" style="font-size:15px;"> <colgroup> <col width="100px"> <col width="200px"> <col width="100px"> <col width="200px"> </colgroup> <tr height="21"> <td height="21"><b>Januar</b></td> <td></td> <td><b>April</b></td> <td></td> </tr><tr height="21"> <td height="21"></td> <td><nobr>Mo 05. Tanzen</nobr></td> <td></td> <td><nobr>Mo 06. Tanzen</nobr></td> </tr><tr height="21"> <td height="21"></td> <td><nobr>Mo 12. Tanzen</nobr></td> <td></td> <td><nobr>Mo 13. Tanzen</nobr></td> </tr><tr height="21"> <td height="21"></td> <td><nobr>Mo 26. Tanzen</nobr></td> <td></td> <td><nobr>Mo 27. Tanzen</nobr></td> </tr><tr height="21"> <td height="21"><b>Februar</b></td> <td></td> <td><b>Mai</b></td> <td></td> </tr><tr height="21"> <td height="21"></td> <td><nobr>Mo 02. Tanzen</nobr></td> <td></td> <td><nobr>Mo 04. Tanzen</nobr></td> </tr><tr height="21"> <td height="21"></td> <td><nobr>Mo 09. Tanzen</nobr></td> <td></td> <td><nobr>Mo 11. Tanzen</nobr></td> </tr><tr height="21"> <td height="21"></td> <td><nobr>Mo 16. Tanzen</nobr></td> <td></td> <td><nobr>Mo 25. Tanzen</nobr></td> </tr><tr height="21"> <td height="21"><b>März</b></td> <td></td> <td><b>Juni</b></td> <td></td> </tr><tr height="21"> <td height="21"></td> <td><nobr>Mo 02. Tanzen</nobr></td> <td></td> <td><nobr>Mo 01. Tanzen</nobr></td> </tr><tr height="21"> <td height="21"></td> <td><nobr>Mo 09. Tanzen</nobr></td> <td></td> <td><nobr>Mo 08. Tanzen</nobr></td> </tr><tr height="21"> <td height="21"></td> <td><nobr>Mo 16. Tanzen</nobr></td> <td></td> <td><nobr>Mo 15. Tanzen</nobr></td> </tr><tr height="21"> <td height="21"></td> <td><nobr>Mo 30. Tanzen</nobr></td> <td></td> <td><nobr>Mo 29. Tanzen</nobr></td> </tr><tr height="21"> <td height="21"><b>April</b></td> <td></td> <td><b>Juli</b></td> <td></td> </tr><tr height="21"> <td height="21"></td> <td><nobr>Mo 06. Tanzen</nobr></td> <td></td> <td><nobr>Mo 06. Tanzen</nobr></td> </tr><tr height="21"> <td height="21"></td> <td><nobr>Mo 13. Tanzen</nobr></td> <td></td> <td><nobr>Mo 13. Tanzen</nobr></td> </tr><tr height="21"> <td height="21"></td> <td><nobr>Mo 27. Tanzen</nobr></td> <td></td> <td><nobr> </nobr></td> </tr></table>

<br>

<center><i><b>Schauen Sie einfach mal bei uns herein (Egal ob Tanzen oder Singen). Wir freuen uns!</b></i>
</center>
